name: facebook_app_events
description: Flutter plugin for Facebook Analytics and App Events
version: 0.0.2
author: Oddbit Team <flutter@oddbit.id>
homepage: https://github.com/oddbit/flutter_facebook_app_events

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: id.oddbit.flutter.facebook_app_events
    pluginClass: FacebookAppEventsPlugin